DROP TABLE IF EXISTS ODONTOLOGO; CREATE TABLE ODONTOLOGO (ID LONG AUTO_INCREMENT PRIMARY KEY, MATRICULA VARCHAR(50) NOT NULL , NOMBRE VARCHAR(50) NOT NULL, APELLIDO VARCHAR(50) NOT NULL);


-- para test --
INSERT INTO ODONTOLOGO(MATRICULA, NOMBRE, APELLIDO) VALUES ('ABC123', 'Digital', 'House');
INSERT INTO ODONTOLOGO(MATRICULA, NOMBRE, APELLIDO) VALUES ('ABC123', 'Oscar', 'Piedrahita');

